// Auto-generated by update_index.bat - DO NOT EDIT MANUALLY 
window.TERMINAL_DATA = { 
  credentials: { 
    "TEST1": "data" 
    ,"TEST2": "REBECCA" 
    ,"TEST3": "SCHMITZ" 
  }, 
  files: { 
    "data": [ 
        "NOTIFICATIONS.txt" 
        ,"test1.txt" 
        ,"welcome.txt" 
    ] 
    ,"REBECCA": [ 
        "NOTIFICATIONS.txt" 
        ,"sch.txt" 
    ] 
    ,"SCHMITZ": [ 
        "NOTIFICATIONS.txt" 
        ,"sch.txt" 
    ] 
  } 
}; 
